# Generated by Django 6.0.5 on 2026-08-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationimage',
            options={'ordering': ['created_at'], 'verbose_name': 'تصویر اقامتگاه', 'verbose_name_plural': 'تصاویر اقامتگاه\u200cها'},
        ),
    ]
