# Generated by Django 6.0.5 on 2026-09-15 15:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
