# Generated by Django 6.0.5 on 2026-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_alter_accommodation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='code',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='کد اقامتگاه'),
        ),
    ]
