# Generated by Django 6.0.5 on 2026-09-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_alter_accommodation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خروج'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده')], max_length=16, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_accommodations', to=settings.AUTH_USER_MODEL, verbose_name='رزرو شده توسط'),
        ),
        migrations.AddConstraint(
            model_name='accommodation',
            constraint=models.CheckConstraint(condition=models.Q(('check_in__lt', models.F('check_out'))), name='check_in_before_check_out'),
        ),
    ]
