# Generated by Django 6.0.5 on 2026-09-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_alter_accommodation_reserved_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accommodation',
            name='check_in_before_check_out',
        ),
    ]
