# Generated by Django 6.0.5 on 2026-09-10 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر وارد کنید.', regex='^09\\d{9}$')]),
        ),
    ]
