# Generated by Django 6.0.5 on 2026-09-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_estate_delete_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='image',
        ),
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='estate/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.estate')),
            ],
            options={
                'verbose_name': 'تصویر ملک',
                'verbose_name_plural': 'تصاویر املاک',
                'ordering': ['created_at'],
            },
        ),
    ]
