# Generated by Django 6.0.5 on 2026-09-23 18:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_remove_estate_image_estateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='توضیحات'),
        ),
    ]
