# Generated by Django 6.0.5 on 2026-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_estate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
