# Generated by Django 6.0.5 on 2026-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_alter_estate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس مالک'),
        ),
    ]
