# Generated by Django 6.0.5 on 2026-09-24 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_alter_estate_owner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='owner_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر وارد کنید.', regex='^09\\d{9}$')], verbose_name='شماره تماس مالک'),
        ),
    ]
