# Generated by Django 6.0.5 on 2026-09-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_alter_estate_owner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
    ]
