# Generated by Django 6.0.5 on 2026-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_estate_is_vip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.RemoveField(
            model_name='estate',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='excluded_services',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='included_services',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='start_date',
        ),
        migrations.AddField(
            model_name='estate',
            name='area',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ'),
        ),
        migrations.AddField(
            model_name='estate',
            name='construction_year',
            field=models.PositiveIntegerField(default=0, verbose_name='سال ساخت'),
        ),
        migrations.AddField(
            model_name='estate',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='estate',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='estate',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='استخر'),
        ),
        migrations.AddField(
            model_name='estate',
            name='has_storage',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
        migrations.AddField(
            model_name='estate',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد اتاق'),
        ),
        migrations.AddField(
            model_name='estate',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت کل'),
        ),
    ]
