# Generated by Django 6.0.5 on 2026-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_alter_estate_options_remove_estate_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.PositiveIntegerField(verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='construction_year',
            field=models.PositiveIntegerField(verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='floor',
            field=models.IntegerField(verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rooms',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد اتاق'),
        ),
    ]
