# Generated by Django 6.0.5 on 2026-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_alter_estate_area_alter_estate_construction_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت کل'),
        ),
    ]
