# Generated by Django 6.0.5 on 2026-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_alter_estate_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت کل'),
        ),
    ]
